apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: citramac-production

resources:
  - ../../base

images:
  - name: citramac-backend
    newName: citramac-backend
    newTag: unset
  - name: citramac-frontend
    newName: citramac-frontend
    newTag: unset

replicas:
  - name: citramac-backend
    count: 3
  - name: citramac-frontend
    count: 3
  - name: citramac-celery-worker
    count: 3

configMapGenerator:
  - name: citramac-backend-config
    behavior: merge
    literals:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_DEBUG=False

patches:
  - target:
      kind: Ingress
      name: citramac
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: citramac.example.invalid
      - op: replace
        path: /spec/rules/0/host
        value: citramac.example.invalid
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-production
  - target:
      kind: ExternalSecret
      name: citramac-backend-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: citramac/production/backend
  - target:
      kind: ExternalSecret
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: citramac/production/monitoring
  - target:
      kind: Deployment
      name: citramac-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: citramac-backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 16
