# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registry', '0012_patient_archive_reason_patient_archived_at_and_more'),
        ('mhp_program', '0006_rls_client_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsychosocialassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biopsychosocial_assessments', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='careteammembership',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_team_memberships', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_reviews', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='psychotherapysession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psychotherapy_sessions', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='rehabmilestone',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='mhp_program.sudrehabplan'),
        ),
        migrations.AlterField(
            model_name='reviewofsystementry',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_of_systems', to='mhp_program.biopsychosocialassessment'),
        ),
        migrations.AlterField(
            model_name='substanceuseentry',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substance_use_entries', to='mhp_program.biopsychosocialassessment'),
        ),
        migrations.AlterField(
            model_name='sudrehabplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sud_rehab_plans', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='supervisionrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_requests', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='urinedrugscreen',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urine_drug_screens', to='mhp_program.sudrehabplan'),
        ),
    ]
