# Generated by Django 5.2.17 on 2026-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline_sync", "0002_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncablerecord",
            name="server_entity_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
