# Generated by Django 5.2.17 on 2026-08-13 08:38

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical_encounter", "0001_initial"),
        ("tenancy", "0002_branch_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentalStatusExam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("appearance", models.TextField(blank=True)),
                ("behavior", models.TextField(blank=True)),
                ("speech", models.TextField(blank=True)),
                ("mood", models.TextField(blank=True)),
                ("affect", models.TextField(blank=True)),
                ("thought_process", models.TextField(blank=True)),
                ("thought_content", models.TextField(blank=True)),
                ("perception", models.TextField(blank=True)),
                ("cognition", models.TextField(blank=True)),
                ("insight", models.TextField(blank=True)),
                ("judgment", models.TextField(blank=True)),
                ("plan", models.TextField(blank=True)),
                (
                    "risk_assessment",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured SI/HI flags, e.g. {'suicidal_ideation': false, 'homicidal_ideation': false, 'notes': ''}",
                    ),
                ),
                ("risk_escalated_to_supervisor", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mental_status_exams",
                        to="clinical_encounter.encounter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("systolic_bp", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("diastolic_bp", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("heart_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("respiratory_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "temperature_c",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("spo2", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "height_cm",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=1, editable=False, max_digits=5, null=True
                    ),
                ),
                (
                    "bsa",
                    models.DecimalField(
                        blank=True, decimal_places=2, editable=False, max_digits=4, null=True
                    ),
                ),
                (
                    "esi_acuity_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Emergency Severity Index, 1 (most acute) to 5 (least).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="ESI acuity level",
                    ),
                ),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="clinical_encounter.encounter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
