# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_encounter', '0004_alter_clinicalorder_encounter_and_more'),
        ('triage', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalstatusexam',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mental_status_exams', to='clinical_encounter.encounter'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_signs', to='clinical_encounter.encounter'),
        ),
    ]
