# Generated by Django 5.2.17 on 2026-10-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_mentalstatusexam_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='blood_glucose_mmol',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Blood glucose (mmol/L)'),
        ),
    ]
