# Generated by Django 5.2.17 on 2026-08-13 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IcdCodeIndex",
            fields=[
                ("code", models.CharField(max_length=16, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "ICD-11 code",
                "verbose_name_plural": "ICD-11 codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LoincCodeIndex",
            fields=[
                ("code", models.CharField(max_length=16, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "LOINC code",
                "verbose_name_plural": "LOINC codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="NationalDrugIndex",
            fields=[
                ("code", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("generic_name", models.CharField(max_length=255)),
                ("form", models.CharField(blank=True, max_length=100)),
                ("strength", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "national drug index entry",
                "ordering": ["generic_name"],
            },
        ),
        migrations.CreateModel(
            name="ShaTransactionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("MEMBER_VERIFICATION", "Member Verification"),
                            ("PRE_AUTHORIZATION", "Pre-Authorization"),
                            ("E_CLAIM", "E-Claim"),
                        ],
                        max_length=32,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
