# Generated by Django 5.2.17 on 2026-08-13 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dha_interop", "0003_seed_loinc"),
    ]

    operations = [
        migrations.CreateModel(
            name="FhirResourceCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True)),
                (
                    "resource_type",
                    models.CharField(help_text="e.g. Bundle, Composition", max_length=64),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUTBOUND", "Outbound"), ("INBOUND", "Inbound")], max_length=16
                    ),
                ),
                ("fhir_json", models.JSONField()),
                ("related_object_type", models.CharField(blank=True, max_length=100)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CACHED", "Cached (not yet transmitted)"),
                            ("SENT", "Sent"),
                            ("RECEIVED", "Received"),
                            ("FAILED", "Failed"),
                        ],
                        default="CACHED",
                        max_length=16,
                    ),
                ),
                ("transmission_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TerminologySyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ICD11", "ICD-11 (WHO)"),
                            ("LOINC", "LOINC"),
                            ("NATIONAL_DRUG_INDEX", "National Drug Index"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED_NOT_CONFIGURED", "Skipped — source not configured"),
                        ],
                        max_length=32,
                    ),
                ),
                ("records_synced", models.PositiveIntegerField(default=0)),
                ("detail", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
