# Generated by Django 5.2.17 on 2026-08-13 07:22

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("GENERAL_HOSPITAL", "General Hospital"),
                            ("MENTAL_HEALTH_CCP", "Mental Health / CCP Centre"),
                            ("DISPENSARY", "Dispensary / Level 2-3"),
                            ("CLINIC", "Outpatient Clinic"),
                        ],
                        max_length=32,
                    ),
                ),
                ("dha_facility_code", models.CharField(blank=True, max_length=64)),
                ("sha_provider_code", models.CharField(blank=True, max_length=64)),
                ("theme_overrides", models.JSONField(blank=True, default=dict)),
                ("enabled_modules", models.JSONField(blank=True, default=list)),
                (
                    "isolation_mode",
                    models.CharField(
                        choices=[("SHARED", "Shared"), ("DEDICATED_DB", "Dedicated")],
                        default="SHARED",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_branches", models.IntegerField()),
                ("max_staff_seats", models.IntegerField()),
                ("included_modules", models.JSONField(blank=True, default=list)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "facility_level",
                    models.CharField(
                        choices=[
                            ("L2", "Level 2"),
                            ("L3", "Level 3"),
                            ("L4", "Level 4"),
                            ("L5", "Level 5"),
                            ("L6", "Level 6"),
                        ],
                        max_length=2,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("gps_coordinates", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "branches",
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancy.subscriptionplan",
            ),
        ),
    ]
