# Generated by Django 5.2.17 on 2026-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_branch_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_domains',
            field=models.JSONField(blank=True, default=list, help_text="Email domains (e.g. 'cafric.org') that route to this tenant at login."),
        ),
        migrations.AddField(
            model_name='organization',
            name='login_image_url',
            field=models.URLField(blank=True, help_text='Optional background image for the tenant login panel.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#006e51', help_text="Hex color, e.g. #006e51 — overrides the default brand green on this tenant's login page only.", max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
