# Generated by Django 5.2.17 on 2026-08-26 08:36

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_org_multivertical_and_subscription"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subscription",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="branch",
            name="mfl_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="branch",
            name="sha_api_credentials_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="sub_county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="sub_county",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
