# Generated by Django 5.2.17 on 2026-08-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_alter_subscription_managers_alter_branch_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private"),
                    ("PUBLIC", "Public"),
                    ("FAITH_BASED", "Faith-Based"),
                    ("NGO", "NGO / Not-for-profit"),
                    ("PARTNERSHIP", "Partnership"),
                    ("OTHER", "Other"),
                ],
                default="PRIVATE",
                max_length=16,
            ),
        ),
    ]
