# Generated by Django 5.2.17 on 2026-09-02 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_platformbranding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email_from_address",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Cafric Demo <notifications@cafric.org>'. Blank uses the platform default.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_host_password_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_host_user",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_use_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="PlatformEmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("host_user", models.CharField(blank=True, max_length=255)),
                ("host_password_encrypted", models.TextField(blank=True)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("default_from_email", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "platform email settings",
            },
        ),
    ]
