# Generated by Django 5.2.17 on 2026-09-15 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0008_organization_email_from_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sms_access_key_encrypted",
            field=models.TextField(
                blank=True, help_text="Onfon 'Access Key' (sent as the AccessKey header)."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_api_key_encrypted",
            field=models.TextField(blank=True, help_text="Onfon 'API Key'."),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_client_id",
            field=models.CharField(blank=True, help_text="Onfon 'Client ID'.", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_provider",
            field=models.CharField(
                choices=[("onfon", "Onfon Media")], default="onfon", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_sender_id",
            field=models.CharField(
                blank=True,
                help_text="Onfon 'Sender ID' — must be an Approved Sender ID on your Onfon account.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PlatformSmsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("onfon", "Onfon Media")], default="onfon", max_length=20
                    ),
                ),
                ("sender_id", models.CharField(blank=True, max_length=32)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("access_key_encrypted", models.TextField(blank=True)),
                ("api_key_encrypted", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "platform sms settings",
            },
        ),
    ]
