# Generated by Django 5.2.17 on 2026-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_organization_sms_access_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbranding',
            name='theme_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
