# Generated by Django 5.2.17 on 2026-09-29 07:23

import apps.tenancy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='past_due_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='SubscriptionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_days_before', models.JSONField(blank=True, default=apps.tenancy.models._default_reminder_days)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=14)),
                ('renewal_contact', models.CharField(blank=True, help_text="e.g. 'billing@example.com or +254 700 000 000'. Shown in every reminder.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscription policy',
            },
        ),
    ]
