# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_encounter', '0004_alter_clinicalorder_encounter_and_more'),
        ('lims', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='clinical_encounter.encounter'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='lab_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='lims.laborder'),
        ),
        migrations.AlterField(
            model_name='labspecimen',
            name='lab_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='lims.laborder'),
        ),
    ]
