# Generated by Django 5.2.17 on 2026-08-13 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("branch_id", models.UUIDField(blank=True, null=True)),
                ("actor_user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("actor_role", models.CharField(blank=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=150)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("field_diff", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name_plural": "audit log entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
