# Generated by Django 5.2.17 on 2026-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sysadmin_audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                ],
                max_length=20,
            ),
        ),
    ]
