# Generated by Django 5.2.17 on 2026-09-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin_audit', '0003_alter_auditlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ERASURE', 'Right-to-Erasure Executed'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('DISCOVERY_FAILED', 'Tenant Discovery Failed')], max_length=20),
        ),
    ]
