# Generated by Django 5.2.17 on 2026-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin_audit', '0006_append_only_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ERASURE', 'Right-to-Erasure Executed'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('DISCOVERY_FAILED', 'Tenant Discovery Failed'), ('ARCHIVE', 'Record Archived'), ('RESTORE', 'Record Restored from Archive'), ('LEGAL_HOLD', 'Legal Hold Changed'), ('SUPPORT_ACCESS', 'Platform Support Access (tenant-approved)'), ('EXPORT', 'Patient Record Exported (data subject request)')], max_length=20),
        ),
    ]
