# Generated by Django 5.2.17 on 2026-08-13 08:25

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_branch_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("HISTORICAL", "Historical File Scans"),
                            ("CURRENT", "Current Clinical Records"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "upi",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Unique Personal Identifier (IPRS)",
                    ),
                ),
                (
                    "uhid_number",
                    models.CharField(blank=True, max_length=64, verbose_name="UHID Number"),
                ),
                ("citramac_number", models.CharField(blank=True, max_length=32, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("middle_other_names", models.CharField(blank=True, max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("occupation", models.CharField(blank=True, max_length=150)),
                ("employment_status", models.CharField(blank=True, max_length=32)),
                ("living_with_disability", models.BooleanField(default=False)),
                ("national_id", models.CharField(blank=True, max_length=32)),
                ("passport_number", models.CharField(blank=True, max_length=32)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "allergy_status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("ACTIVE_ALLERGIES", "Active Allergies"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("referral_source", models.CharField(blank=True, max_length=255)),
                ("referral_mode", models.CharField(blank=True, max_length=255)),
                ("referral_date", models.DateField(blank=True, null=True)),
                (
                    "patient_category",
                    models.CharField(
                        choices=[
                            ("OUTPATIENT", "Outpatient"),
                            ("INPATIENT", "Inpatient"),
                            ("POSTTREATMENT_SUPPORT", "Posttreatment Support"),
                        ],
                        default="OUTPATIENT",
                        max_length=32,
                    ),
                ),
                ("insurer_details", models.CharField(blank=True, max_length=255)),
                ("consent_data_sharing", models.BooleanField(default=False)),
                ("consent_captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="client_registry.attachment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_of_kin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="client_registry.emergencycontact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceCoverage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("SHA_PRIMARY", "SHA Primary Healthcare Fund"),
                            ("SHA_SHIF", "SHA Social Health Insurance Fund"),
                            ("SHA_ECCIF", "SHA Emergency, Chronic & Critical Illness Fund"),
                            ("PRIVATE", "Private"),
                            ("CORPORATE", "Corporate"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("policy_number", models.CharField(blank=True, max_length=100)),
                ("corporate_account", models.CharField(blank=True, max_length=255)),
                ("sha_verified", models.BooleanField(default=False)),
                ("sha_member_status", models.CharField(blank=True, max_length=100)),
                ("sha_premium_compliant", models.BooleanField(default=False)),
                ("sha_last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_coverages",
                        to="client_registry.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contacts",
                to="client_registry.patient",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="client_registry.patient",
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("appointment_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CHECKED_IN", "Checked In"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="client_registry.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AllergyRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("substance", models.CharField(max_length=255)),
                ("reaction", models.CharField(blank=True, max_length=255)),
                ("severity", models.CharField(blank=True, max_length=32)),
                ("noted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_records",
                        to="client_registry.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("uhid_number", ""), _negated=True),
                fields=("organization", "uhid_number"),
                name="unique_uhid_per_org",
            ),
        ),
    ]
