# Generated by Django 5.2.17 on 2026-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_registry", "0006_erasurerequest_rls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"base_manager_name": "all_objects", "ordering": ["scheduled_for"]},
        ),
        migrations.AlterModelOptions(
            name="attachment",
            options={"base_manager_name": "all_objects", "ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="appointment",
            name="mode",
            field=models.CharField(
                choices=[("IN_PERSON", "In Person"), ("PHONE", "Phone"), ("VIDEO", "Video")],
                default="IN_PERSON",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("IDENTITY", "Identity Documents"),
                    ("CLINICAL", "Clinical Documents"),
                    ("ASSESSMENT", "Assessments"),
                    ("REFERRAL", "Referrals"),
                    ("LAB_RESULT", "Lab Results"),
                    ("IMAGING", "Imaging"),
                    ("CONSENT", "Consents"),
                    ("CORRESPONDENCE", "Correspondence"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="doc_status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="document_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="document_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
