# Generated by Django 5.2.17 on 2026-09-09 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_registry", "0007_alter_appointment_options_alter_attachment_options_and_more"),
        ("ipd_ward", "0004_admission_admission_source_admission_admission_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="admission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="ipd_ward.admission",
            ),
        ),
    ]
