# Generated by Django 5.2.17 on 2026-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_registry", "0008_attachment_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/patients/%Y/%m/"),
        ),
    ]
