# Generated by Django 5.2.17 on 2026-09-09 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_registry", "0009_patient_photo"),
        ("tenancy", "0008_organization_email_from_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="citramac_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("citramac_number", ""), _negated=True),
                fields=("citramac_number",),
                name="unique_citramac_number_when_set",
            ),
        ),
    ]
