# Generated by Django 5.2.17 on 2026-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_registry", "0010_alter_patient_citramac_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
