# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registry', '0011_appointment_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('RETENTION_EXPIRED', 'Retention period ended')], max_length=24),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_hold_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='legal_hold_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allergyrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergy_records', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contacts', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='erasurerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erasure_requests', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='insurancecoverage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_coverages', to='client_registry.patient'),
        ),
    ]
