# Generated by Django 5.2.17 on 2026-10-07 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registry', '0012_patient_archive_reason_patient_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergyrecord',
            name='source',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('TRIAGE', 'Triage'), ('CLINICIAN', 'Clinician')], default='CLINICIAN', max_length=12),
        ),
        migrations.AddField(
            model_name='allergyrecord',
            name='verification_status',
            field=models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed (client-reported)'), ('CONFIRMED', 'Confirmed'), ('REFUTED', 'Refuted')], default='CONFIRMED', max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport (foreign national)'), ('REFUGEE_ID', 'Refugee / asylum-seeker ID'), ('ALIEN_ID', 'Alien ID'), ('BIRTH_CERTIFICATE', 'Birth certificate (minor)'), ('NONE', 'None / unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observed description / temporary alias'),
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_status',
            field=models.CharField(choices=[('IDENTIFIED', 'Identified'), ('UNIDENTIFIED', 'Unidentified — provisional record'), ('UNKNOWN', 'Unknown — minimum details only')], default='IDENTIFIED', max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='interpreter',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('KISWAHILI', 'Yes — Kiswahili'), ('OTHER_LOCAL', 'Yes — other local language'), ('SIGN', 'Yes — sign language')], max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='payer',
            field=models.CharField(blank=True, choices=[('SHA', 'SHA'), ('SHA_PRIVATE', 'SHA + private insurer'), ('PRIVATE', 'Private insurance'), ('EMPLOYER', 'Employer scheme'), ('SELF_PAY', 'Self-pay'), ('WAIVER', 'Waiver / charity'), ('UNKNOWN', 'Unknown')], max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('SHE_HER', 'she/her'), ('HE_HIM', 'he/him'), ('THEY_THEM', 'they/them'), ('NOT_SAID', 'Prefer not to say'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Intersex / other'), ('NOT_STATED', 'Not stated')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
