# Generated by Django 5.2.17 on 2026-10-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pathway', '0006_discharge_summary'),
        ('client_registry', '0013_allergyrecord_recorded_by_allergyrecord_source_and_more'),
        ('ipd_ward', '0006_admission_clinical_priority_admission_episode'),
        ('tenancy', '0015_theme_overrides_light_dark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_appointments', to='ipd_ward.admission'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='care_pathway.episodeofcare'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='origin',
            field=models.CharField(choices=[('MANUAL', 'Booked manually'), ('DISCHARGE', 'Booked at discharge'), ('CARE_PLAN', 'Booked from the care plan')], default='MANUAL', max_length=16),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('organization', 'client_request_id'), name='unique_appointment_client_request'),
        ),
    ]
