# Generated by Django 5.2.17 on 2026-08-26 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FAILED_LOGINS", "Failed login spike"),
                            ("MFA_ADOPTION", "Low MFA adoption"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-detected_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["NEW", "INVESTIGATING"])),
                        fields=("organization_id", "category"),
                        name="one_open_alert_per_org_category",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("minimum_password_length", models.PositiveSmallIntegerField(default=12)),
                (
                    "password_complexity",
                    models.CharField(default="Upper, lower, number and symbol", max_length=255),
                ),
                ("password_expiry_days", models.PositiveSmallIntegerField(default=90)),
                ("password_history_count", models.PositiveSmallIntegerField(default=5)),
                ("max_failed_login_attempts", models.PositiveSmallIntegerField(default=5)),
                ("lockout_duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("session_timeout_minutes", models.PositiveSmallIntegerField(default=30)),
                ("max_concurrent_sessions", models.PositiveSmallIntegerField(default=3)),
                ("token_expiry_minutes", models.PositiveSmallIntegerField(default=60)),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=120)),
                ("data_retention_years", models.PositiveSmallIntegerField(default=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "security policy",
            },
        ),
    ]
