# Generated by Django 5.2.17 on 2026-09-29 07:23

import apps.retention.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_registry', '0012_patient_archive_reason_patient_archived_at_and_more'),
        ('tenancy', '0014_subscription_past_due_since_subscription_started_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('reason', models.CharField(choices=[('RETENTION_EXPIRED', 'Retention period ended')], default='RETENTION_EXPIRED', max_length=24)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('archived_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'verbose_name_plural': 'archive batches',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_floor_years', models.PositiveSmallIntegerField(default=apps.retention.models._default_floor_years)),
                ('mental_health_floor_years', models.PositiveSmallIntegerField(default=apps.retention.models._default_floor_years)),
                ('financial_floor_years', models.PositiveSmallIntegerField(default=apps.retention.models._default_floor_years)),
                ('minor_clock_start_age', models.PositiveSmallIntegerField(blank=True, default=18, null=True)),
                ('floor_verified', models.BooleanField(default=False)),
                ('floor_source', models.TextField(blank=True, help_text='The legal instrument / DHA guidance the floor values were confirmed against.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('forecast_windows_days', models.JSONField(blank=True, default=apps.retention.models._default_forecast_windows)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'retention platform settings',
            },
        ),
        migrations.CreateModel(
            name='RetentionScanRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('OK', 'Completed'), ('SKIPPED_DISABLED', 'Skipped — scan disabled for this organization'), ('FAILED', 'Failed')], max_length=20)),
                ('due_count', models.PositiveIntegerField(default=0)),
                ('forecast', models.JSONField(blank=True, default=dict)),
                ('floor_verified', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retention.archivebatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveBatchItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_activity_at', models.DateTimeField()),
                ('retention_years', models.PositiveSmallIntegerField()),
                ('retention_ends_on', models.DateField()),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('ARCHIVED', 'Archived'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('skip_reason', models.CharField(blank=True, max_length=120)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='retention.archivebatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_batch_items', to='client_registry.patient')),
            ],
            options={
                'ordering': ['retention_ends_on'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('batch', 'patient'), name='unique_patient_per_batch')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinical_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mental_health_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('financial_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scan_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'organization retention policies',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='unique_retention_policy_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
