apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: citramac-staging

resources:
  - ../../base

images:
  - name: citramac-backend
    newName: citramac-backend
    newTag: unset
  - name: citramac-frontend
    newName: citramac-frontend
    newTag: unset

replicas:
  - name: citramac-backend
    count: 2
  - name: citramac-frontend
    count: 2
  - name: citramac-celery-worker
    count: 1

configMapGenerator:
  - name: citramac-backend-config
    behavior: merge
    literals:
      - DJANGO_SETTINGS_MODULE=config.settings.staging
      - DJANGO_DEBUG=False

patches:
  - target:
      kind: Ingress
      name: citramac
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.citramac.example.invalid
      - op: replace
        path: /spec/rules/0/host
        value: staging.citramac.example.invalid
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
  - target:
      kind: ExternalSecret
      name: citramac-backend-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: citramac/staging/backend
  - target:
      kind: ExternalSecret
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: citramac/staging/monitoring
