# Generated by Django 5.2.17 on 2026-10-08 09:56

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pathway', '0005_seed_admission_valuesets'),
        ('client_registry', '0013_allergyrecord_recorded_by_allergyrecord_source_and_more'),
        ('clinical_encounter', '0005_encounter_episode'),
        ('dha_interop', '0004_fhirresourcecache_terminologysyncrun'),
        ('ipd_ward', '0006_admission_clinical_priority_admission_episode'),
        ('tenancy', '0015_theme_overrides_light_dark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Signed')], default='IN_PROGRESS', max_length=12)),
                ('disposition', models.CharField(blank=True, max_length=32)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_status', models.TextField(blank=True)),
                ('treatment_summary', models.TextField(blank=True)),
                ('legal_status_at_discharge', models.TextField(blank=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('draft_saved_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_role', models.CharField(blank=True, max_length=100)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to='ipd_ward.admission')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnoses', models.ManyToManyField(blank=True, related_name='+', to='clinical_encounter.diagnosiscode')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinical_encounter.encounter')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='care_pathway.episodeofcare')),
                ('follow_up_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_registry.appointment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to='client_registry.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_by', to='care_pathway.dischargesummary')),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DischargeMedicationLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dha_interop.nationaldrugindex')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinical_encounter.prescriptionitem')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='care_pathway.dischargesummary')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='dischargesummary',
            constraint=models.UniqueConstraint(fields=('admission', 'version'), name='unique_discharge_version_per_admission'),
        ),
    ]
