# Generated by Django 5.2.17 on 2026-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical_encounter", "0002_rls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosiscode",
            options={"base_manager_name": "all_objects", "ordering": ["-noted_at"]},
        ),
        migrations.AddField(
            model_name="diagnosiscode",
            name="clinical_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnosiscode",
            name="diagnostic_criteria_met",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="diagnosiscode",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("HISTORICAL", "Historical"),
                    ("RESOLVED", "Resolved"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
