# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registry', '0012_patient_archive_reason_patient_archived_at_and_more'),
        ('clinical_encounter', '0003_alter_diagnosiscode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalorder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clinical_encounter.encounter'),
        ),
        migrations.AlterField(
            model_name='diagnosiscode',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clinical_encounter.encounter'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical_encounter.encounter'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clinical_encounter.prescription'),
        ),
        migrations.AlterField(
            model_name='referralpacket',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='clinical_encounter.encounter'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soap_notes', to='clinical_encounter.encounter'),
        ),
    ]
