# Generated by Django 5.2.17 on 2026-10-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pathway', '0001_initial'),
        ('clinical_encounter', '0004_alter_clinicalorder_encounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='care_pathway.episodeofcare'),
        ),
    ]
