# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_claims', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='insurance_claims.insuranceclaim'),
        ),
    ]
