# Generated by Django 5.2.17 on 2026-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_mfa_channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=8),
        ),
    ]
