# Generated by Django 5.2.17 on 2026-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_preferred_mfa_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_on_duty",
            field=models.BooleanField(default=False),
        ),
    ]
