# Generated by Django 5.2.17 on 2026-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_on_duty"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[("PLATFORM", "Platform staff"), ("ORG_TEMPLATE", "Organization template")],
                default="ORG_TEMPLATE",
                max_length=16,
            ),
        ),
    ]
