# Generated by Django 5.2.17 on 2026-09-18 08:00
#
# Lets ActivationInvite.organization be NULL for a platform-staff invite
# (organization=None, same convention as User.organization/Role.organization)
# so PlatformStaffViewSet.create() can issue a real ActivationInvite instead
# of the OTP-code email it used before. No RLS policy change is needed:
# migrations/0002_rls.py's accounts_activationinvite policy already grants
# access via its `is_platform_admin` clause, and every NULL-organization row
# here is only ever created/read inside platform_admin_context().
#
# Reversible only while no NULL-organization rows exist — once a real
# platform-staff invite has been issued, rolling this back requires
# backfilling or deleting those rows first (Postgres can't add a NOT NULL
# constraint back over existing NULLs).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_avatar'),
        ('tenancy', '0009_organization_sms_access_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationinvite',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization'),
        ),
    ]
