# Generated by Django 5.2.17 on 2026-09-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_country'),
        ('accounts', '0009_alter_activationinvite_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='staff_members',
                to='tenancy.department',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='access_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='access_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
