# Generated by Django 5.2.17 on 2026-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipd_ward", "0002_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("RESERVED", "Reserved"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="AVAILABLE",
                max_length=16,
            ),
        ),
    ]
