# Generated by Django 5.2.17 on 2026-09-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipd_ward", "0003_alter_bed_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="admission_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admission",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("VOLUNTARY", "Voluntary Admission"),
                    ("INVOLUNTARY", "Involuntary Admission"),
                ],
                default="VOLUNTARY",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="associated_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="authorizing_professional",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="admission",
            name="capacity_assessed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="clinical_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="consent_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="consent_obtained_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="consent_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Consent Pending"),
                    ("OBTAINED", "Consent Obtained"),
                    ("DECLINED", "Consent Declined"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="handover_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="initial_care_priorities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="legal_order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="legal_order_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="admission",
            name="legal_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="legal_review_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="legal_status",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="admission",
            name="next_of_kin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="next_of_kin_notification",
            field=models.CharField(
                choices=[
                    ("NOT_NOTIFIED", "Not Yet Notified"),
                    ("NOTIFIED", "Notified"),
                    ("NOT_APPLICABLE", "Notification Not Applicable"),
                    ("UNABLE_TO_REACH", "Unable to Reach"),
                ],
                default="NOT_NOTIFIED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="observation_level",
            field=models.CharField(
                choices=[
                    ("ROUTINE", "Routine Observation"),
                    ("ENHANCED", "Enhanced Observation"),
                    ("CLOSE", "Close Observation"),
                    ("CONTINUOUS", "Continuous Observation"),
                ],
                default="ROUTINE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="oversight_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="primary_care_team",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="admission",
            name="primary_diagnosis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="admission",
            name="priority",
            field=models.CharField(
                choices=[("ROUTINE", "Routine"), ("URGENT", "Urgent"), ("EMERGENCY", "Emergency")],
                default="ROUTINE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="reason_for_admission",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="risk_absconding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admission",
            name="risk_medical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admission",
            name="risk_self_harm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admission",
            name="risk_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admission",
            name="risk_to_others",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admission",
            name="safety_actions",
            field=models.TextField(blank=True),
        ),
    ]
