# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_registry', '0012_patient_archive_reason_patient_archived_at_and_more'),
        ('ipd_ward', '0004_admission_admission_source_admission_admission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='client_registry.patient'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='ipd_ward.ward'),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mar_entries', to='ipd_ward.admission'),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to='ipd_ward.admission'),
        ),
    ]
