# Generated by Django 5.2.17 on 2026-10-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pathway', '0001_initial'),
        ('ipd_ward', '0005_alter_admission_patient_alter_bed_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='clinical_priority',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN')], max_length=8),
        ),
        migrations.AddField(
            model_name='admission',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='care_pathway.episodeofcare'),
        ),
    ]
