# Generated by Django 5.2.17 on 2026-09-02 06:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccp_program", "0004_rls_extensions"),
        ("tenancy", "0007_platformbranding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biopsychosocialassessment",
            options={"base_manager_name": "all_objects", "ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="admission_type_at_intake",
            field=models.CharField(
                choices=[("NEW", "New Admission"), ("READMISSION", "Readmission")],
                default="NEW",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="collateral_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="current_medications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="date_of_intake",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="family_psychiatric_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="forensic_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="hpi_duration",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="hpi_onset_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="hpi_severity",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="injecting_drug_use",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="level_of_care",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INPATIENT", "Inpatient"),
                    ("OUTPATIENT", "Outpatient"),
                    ("PARTIAL", "Partial"),
                    ("RESIDENTIAL", "Residential"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="main_drug_problem",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="next_steps",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="other_main_drug_problem",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="past_medical_surgical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="plan_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="premorbid_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="self_harm_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("HIGH", "High"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="substance_use_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="suicide_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("HIGH", "High"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="treatment_before",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="vegetative_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="violence_risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("LOW", "Low"),
                    ("MODERATE", "Moderate"),
                    ("HIGH", "High"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="biopsychosocialassessment",
            name="withdrawal_risk",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ReviewOfSystemEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_of_systems",
                        to="ccp_program.biopsychosocialassessment",
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubstanceUseEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("substance", models.CharField(max_length=100)),
                ("first_use", models.DateField(blank=True, null=True)),
                ("last_use", models.DateField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, max_length=32)),
                ("route", models.CharField(blank=True, max_length=32)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substance_use_entries",
                        to="ccp_program.biopsychosocialassessment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
