# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstockitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='pharmacy.store'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.drugstockitem'),
        ),
    ]
