# Generated by Django 5.2.17 on 2026-10-07 12:27

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_registry', '0013_allergyrecord_recorded_by_allergyrecord_source_and_more'),
        ('tenancy', '0015_theme_overrides_light_dark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachIncident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reported_role', models.CharField(choices=[('CONTROLLER', 'Reported by the facility (data controller)'), ('PROCESSOR', 'Reported by the platform (data processor)')], max_length=10)),
                ('became_aware_at', models.DateTimeField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('involves_health_data', models.BooleanField(default=True)),
                ('data_categories', models.TextField(blank=True)),
                ('subjects_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('UNLIKELY', 'Unlikely to result in a risk to data subjects'), ('RISK', 'Likely to result in a risk of harm'), ('HIGH_RISK', 'Likely to result in a high risk')], max_length=10)),
                ('containment_actions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONTAINED', 'Contained'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-became_aware_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BreachNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track', models.CharField(choices=[('TENANT_CONTROLLER', 'Platform → facility (as data controller)'), ('ODPC', 'Office of the Data Protection Commissioner'), ('DHA', 'Digital Health Agency (Chief Executive Officer)'), ('DATA_SUBJECTS', 'Affected data subjects')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('due_at', models.DateTimeField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='compliance.breachincident')),
                ('notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'ordering': ['due_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Access / copy of health record'), ('PORTABILITY', 'Data portability'), ('CORRECTION', 'Correction of false or misleading data'), ('OBJECTION', 'Objection to processing'), ('RESTRICTION', 'Restriction of processing')], max_length=12)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_in_writing', models.BooleanField(default=True)),
                ('requester', models.CharField(choices=[('SELF', 'Client'), ('REPRESENTATIVE', 'Authorised representative')], default='SELF', max_length=16)),
                ('requester_name', models.CharField(blank=True, max_length=150)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('APPROVED', 'Verified & approved'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined')], default='RECEIVED', max_length=10)),
                ('identity_verification', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_subject_requests', to='client_registry.patient')),
            ],
            options={
                'ordering': ['-received_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlatformComplianceSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('dpo_name', models.CharField(blank=True, max_length=150)),
                ('dpo_email', models.EmailField(blank=True, max_length=254)),
                ('dpo_phone', models.CharField(blank=True, max_length=32)),
                ('warranty_version', models.CharField(blank=True, max_length=32)),
                ('warranty_text', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportAccessGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='Support ticket reference')),
                ('duration_hours', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_requests', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TenantComplianceProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('odpc_registration_number', models.CharField(blank=True, max_length=64)),
                ('odpc_registration_expires_on', models.DateField(blank=True, null=True)),
                ('odpc_evidence', models.FileField(blank=True, null=True, upload_to='compliance/odpc/%Y/%m/')),
                ('odpc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dpa_version', models.CharField(blank=True, max_length=32, verbose_name='Data processing agreement version')),
                ('dpa_signed_on', models.DateField(blank=True, null=True)),
                ('warranty_version', models.CharField(blank=True, max_length=32)),
                ('warranty_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dpo_name', models.CharField(blank=True, max_length=150)),
                ('dpo_email', models.EmailField(blank=True, max_length=254)),
                ('dpo_phone', models.CharField(blank=True, max_length=32)),
                ('odpc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('warranty_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='breachincident',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_breach_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='breachnotification',
            constraint=models.UniqueConstraint(fields=('incident', 'track'), name='one_track_per_incident'),
        ),
        migrations.AddConstraint(
            model_name='tenantcomplianceprofile',
            constraint=models.UniqueConstraint(fields=('organization',), name='one_compliance_profile_per_org'),
        ),
    ]
